# Generated by Django 4.2.4 on 2023-09-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Известные женщины', 'verbose_name_plural': 'Известные женщины'},
        ),
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['time_create'], name='women_women_time_cr_21b781_idx'),
        ),
    ]
