# Generated by Django 4.2.5 on 2023-11-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0011_uploadfile_alter_women_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
